export const selectors = {
  homeView: document.querySelector("#home-view"),
  studentView: document.querySelector("#student-view"),
  heroVisual: document.querySelector("#hero-visual"),
  themeModal: document.querySelector("#theme-modal"),
  themeModalTags: document.querySelector("#theme-modal-tags"),
  themeModalSkip: document.querySelector("#theme-modal-skip"),
  recommendationGrid: document.querySelector("#recommendation-grid"),
  recommendationNote: document.querySelector("#recommendation-note"),
  todayQuestionCard: document.querySelector("#today-question-card"),
  topicList: document.querySelector("#topic-list"),
  peopleGrid: document.querySelector("#people-grid"),
  topicResultHead: document.querySelector("#topic-result-head"),
  clearTopic: document.querySelector("#clear-topic"),
  siteSearch: document.querySelector("#site-search"),
  recentQuestions: document.querySelector("#recent-questions"),
  tagCloud: document.querySelector("#tag-cloud"),
};
