export const selectors = {
  homeView: document.querySelector("#home-view"),
  studentView: document.querySelector("#student-view"),
  heroVisual: document.querySelector("#hero-visual"),
  searchModal: document.querySelector("#search-modal"),
  searchModalTags: document.querySelector("#search-modal-tags"),
  searchModalQuestions: document.querySelector("#search-modal-questions"),
  modalSearchInput: document.querySelector("#modal-search-input"),
  todayQuestionCard: document.querySelector("#today-question-card"),
  topicList: document.querySelector("#topic-list"),
  peopleGrid: document.querySelector("#people-grid"),
  peopleMore: document.querySelector("#people-more"),
  topicResultHead: document.querySelector("#topic-result-head"),
  clearTopic: document.querySelector("#clear-topic"),
  siteSearch: document.querySelector("#site-search"),
  noteFeedSection: document.querySelector("#note-feed"),
  noteFeedGrid: document.querySelector("#note-feed-grid"),
};
